services:
  db1:
    container_name: sqlNode1
    image: mcr.microsoft.com/mssql/server:2022-latest
    hostname: publisher
    domainname: lab.local
    environment:
      SA_PASSWORD: "Password1"
      ACCEPT_EULA: "Y"
      MSSQL_AGENT_ENABLED: "true"
      MSSQL_ENABLE_HADR: 1
    ports:
    - "1501:1433"
    extra_hosts:
      sqlNode2.lab.local: "172.16.238.22"
      sqlNode3.lab.local: "172.16.238.23"
    networks:
      mssqlreplicas:
        ipv4_address: 172.16.238.21

  db2:
    container_name: sqlNode2
    image: mcr.microsoft.com/mssql/server:2022-latest
    hostname: subscriber
    domainname: lab.local
    environment:
      SA_PASSWORD: "Password1"
      ACCEPT_EULA: "Y"
      MSSQL_AGENT_ENABLED: "true"
      MSSQL_ENABLE_HADR: 1
    ports:
    - "1502:1433"
    extra_hosts:
      sqlNode1.lab.local: "172.16.238.21"
      sqlNode3.lab.local: "172.16.238.23"
    networks:
      mssqlreplicas:
        ipv4_address: 172.16.238.22

  db3:
    container_name: sqlNode3
    image: mcr.microsoft.com/mssql/server:2022-latest
    hostname: distributor
    domainname: lab.local
    environment:
      SA_PASSWORD: "Password1"
      ACCEPT_EULA: "Y"
      MSSQL_AGENT_ENABLED: "true"
      MSSQL_ENABLE_HADR: 1
    ports:
    - "1503:1433"
    extra_hosts:
      sqlNode1.lab.local: "172.16.238.21"
      sqlNode2.lab.local: "172.16.238.22"
    networks:
      mssqlreplicas:
        ipv4_address: 172.16.238.23

networks:
  mssqlreplicas:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: 172.16.238.0/24
