name: Build

on:
  push:
  pull_request:

jobs:
  build_transaction_replication:
    runs-on: ubuntu-latest
    name: Build Snapshot Replication
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Add hosts to /etc/hosts
        run: |
          sudo echo "127.0.0.1 publisher publisher.lab.local subscriber subscriber.lab.local distributor distributor.lab.local witness witness.lab.local" | sudo tee -a /etc/hosts

      - name: Docker-compose up
        run: |
          docker-compose -f ./mssql-replication-transactions/docker-compose.yaml up -d --remove-orphans

      - name: Docker-compose down
        run: |
          docker-compose -f ./mssql-replication-transactions/docker-compose.yaml down --volumes

  build_readonly_replicas:
    runs-on: ubuntu-latest
    name: Build Snapshot Replication
    steps:
      - name: Checkout
        uses: actions/checkout@v3