name: Build

on:
  push:
  pull_request:

jobs:
  build_docker:
    runs-on: ubuntu-latest
    name: Build Docker image
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: sqlag
          flavor: |
            latest=false
          tags: |
            type=raw,value=ha
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build sqlag Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: false
          tags: ${{ steps.meta.outputs.tags }}
          outputs: type=docker,dest=sql.tar
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: sql
          path: sql.tar

  build_transaction_replication:
    runs-on: ubuntu-latest
    name: Build Snapshot Replication
    needs: [build_docker]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Add hosts to /etc/hosts
        run: |
          sudo echo "127.0.0.1 publisher publisher.lab.local subscriber subscriber.lab.local distributor distributor.lab.local witness witness.lab.local" | sudo tee -a /etc/hosts
      - name: Download artifact
        uses: actions/download-artifact@v3

      - name: Load Docker image
        run: |
          find . -type f -name '*.tar' -exec docker load --input {} \;
          docker image ls -a
      - name: Docker-compose up
        run: |
          docker-compose -f ./mssql-replication-transactions/docker-compose.yaml up -d --remove-orphans
      - name: Docker-compose down
        run: |
          docker-compose -f ./mssql-replication-transactions/docker-compose.yaml down --volumes
