name: Build replication

on:
  push:

jobs:
  run_replication:
    runs-on: ubuntu-latest
    name: Replication transactions
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Add hosts to /etc/hosts
        run: |
          sudo echo "127.0.0.1 publisher publisher.lab.local subscriber subscriber.lab.local distributor distributor.lab.local witness witness.lab.local" | sudo tee -a /etc/hosts
      - name: Docker-compose up
        run: |
          docker-compose -f ./mssql-replication-transactions/docker-compose.yml up -d --remove-orphans
      - name: Sleep for 30 seconds to allow SQL Server to spin up
        run: sleep 30s
        shell: bash

      - name: Grab DockerID's
        run: |
          echo "SQLNODE1=$(docker ps --all --filter name=sqlNode1 --no-trunc --format "{{.ID}}")" >> $GITHUB_ENV
          echo "SQLNODE2=$(docker ps --all --filter name=sqlNode2 --no-trunc --format "{{.ID}}")" >> $GITHUB_ENV
          echo "SQLNODE3=$(docker ps --all --filter name=sqlNode3 --no-trunc --format "{{.ID}}")" >> $GITHUB_ENV

      - name: Make the ReplData directories
        run: |
          docker exec -i $SQLNODE1 mkdir /var/opt/mssql/ReplData
          docker exec -i $SQLNODE2 mkdir /var/opt/mssql/ReplData
          docker exec -i $SQLNODE3 mkdir /var/opt/mssql/ReplData

      - name: Create distributor
        run: |
          docker exec -i $SQLNODE3 /opt/mssql-tools/bin/sqlcmd -S localhost -U SA -P "Password1" < ./mssql-replication-transactions/create_distributor.sql
          docker exec -i $SQLNODE3 /opt/mssql-tools/bin/sqlcmd -S localhost -U SA -P "Password1" < ./mssql-replication-transactions/verify_distributor.sql

      - name: Setup publisher
        run: |
          docker exec -i $SQLNODE1 /opt/mssql-tools/bin/sqlcmd -S localhost -U SA -P "Password1" < ./mssql-replication-transactions/create_publisher.sql
          docker exec -i $SQLNODE1 /opt/mssql-tools/bin/sqlcmd -S localhost -U SA -P "Password1" < ./mssql-replication-transactions/create_sales_db.sql

      - name: Setup subscriber
        run: |
          docker exec -i $SQLNODE2 /opt/mssql-tools/bin/sqlcmd -S localhost -U SA -P "Password1" < ./mssql-replication-transactions/create_sales_db.sql

      - name: Setup replications
        run: |
          docker exec -i $SQLNODE1 /opt/mssql-tools/bin/sqlcmd -S localhost -U SA -P "Password1" < ./mssql-replication-transactions/enable_replications.sql

      - name: Sleep for 10 seconds
        run: sleep 10s
        shell: bash

      - name: Insert extra row
        run: |
          docker exec -i $SQLNODE1 /opt/mssql-tools/bin/sqlcmd -S localhost -U SA -P "Password1" < ./mssql-replication-transactions/insert_extra_row.sql

      - name: Sleep for 10 seconds
        run: sleep 10s
        shell: bash

      - name: Display Status
        run: |
          docker exec -i $SQLNODE3 /opt/mssql-tools/bin/sqlcmd -S localhost -U SA -P "Password1" -Q "SELECT * FROM [distribution].[dbo].[MSdistribution_history]"

      - name: Verify extra row on publisher
        run: |
          docker exec -i $SQLNODE2 /opt/mssql-tools/bin/sqlcmd -S localhost -U SA -P "Password1" < ./mssql-replication-transactions/verify_replication.sql

      - name: Docker-compose down
        run: |
          docker-compose -f ./mssql-replication-transactions/docker-compose.yml down --volumes
